### ISSUE TITLE
No Data Found in Qdrant: Troubleshooting Empty Index 

### ISSUE THREAD

**Issue by yoyoyo2025** [IntelLabs/RAGFoundry#6]
I write a new yaml for retrieval:

# Retrieval Augmentation Configuration
name: retrieval_augmentation_experiment
cache: false
output_path: .

steps:
  - _target_: ragfoundry.processing.dataset_loaders.loaders.LocalLoader
    inputs: train
    filename: mypath/rag/RAGFoundry-main/data/train.jsonl

  - _target_: ragfoundry.processing.dataset_loaders.loaders.LocalLoader
    inputs: test
    filename: mypath/rag/RAGFoundry-main/data/test.jsonl

  - _target_: ragfoundry.processing.local_steps.retrievers.haystack.HaystackRetriever
    inputs: [train,test]
    pipeline_or_yaml_path: mypath/rag/RAGFoundry-main/configs/external/haystack/qdrant.yaml
    docs_key: positive_passages
    query_key: text1  
    retriever_index: train  
    

  - _target_: ragfoundry.processing.local_steps.context.ContextHandler
    inputs: [test]  
    docs_key: positive_passages

  - _target_: ragfoundry.processing.local_steps.prompter.TextPrompter
    inputs: test
    prompt_file: mypath/rag/RAGFoundry-main/configs/prompts/qa-short.txt
    output_key: prompt
    mapping:
      description: text1  
      context: positive_passages

  - _target_: ragfoundry.processing.global_steps.output.OutputData
    inputs: test
    prefix: retrieval_augmentation_output

However, when I open http://127.0.0.1:6333/collections/train, it shows: {
    "result": {
        "status": "green",
        "optimizer_status": "ok",
        "indexed_vectors_count": 0,
        "points_count": 0,
        "segments_count": 8,
        "config": {
            "params": {
                "vectors": {
                    "size": 768,
                    "distance": "Dot",
                    "on_disk": false
                },
                "shard_number": 1,
                "replication_factor": 1,
                "write_consistency_factor": 1,
                "on_disk_payload": true
            },
            "hnsw_config": {
                "m": 16,
                "ef_construct": 100,
                "full_scan_threshold": 10000,
                "max_indexing_threads": 0,
                "on_disk": false
            },
            "optimizer_config": {
                "deleted_threshold": 0.2,
                "vacuum_min_vector_number": 1000,
                "default_segment_number": 0,
                "max_segment_size": null,
                "memmap_threshold": null,
                "indexing_threshold": 20000,
                "flush_interval_sec": 5,
                "max_optimization_threads": null
            },
            "wal_config": {
                "wal_capacity_mb": 32,
                "wal_segments_ahead": 0
            },
            "quantization_config": null
        },
        "payload_schema": {}
    },
    "status": "ok",
    "time": 0.000126005
}

I've noticed that there appears to be no data stored in my Qdrant instance, and I'm unsure of the cause. Could you provide some guidance on how to troubleshoot this issue? Thank you very much.

**Comment by danielfleischer** [comment]
Hi, you need to put some data in Qdrant, it's a DB. See my [comment](https://github.com/IntelLabs/RAGFoundry/issues/4#issuecomment-2282715889) regarding indexing a corpus. 

If you want a simpler example, without the use of a corpus, see the [Pubmed Tutorial](https://github.com/IntelLabs/RAGFoundry/blob/main/docs/pubmed.md).
